VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsDatabaseInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Identifier As String
Public SourceID As Long
Public SourceShortName As String

Public Property Get UniqueName() As String
    UniqueName = SourceShortName
End Property

Public Property Get DisplayName() As String
    DisplayName = SourceShortName
End Property
