<?php


$country_options = array(
'Afghanistan' => 'af',
'Aland Islands' => 'ax',
'Albania' => 'al',
'Algeria' => 'dz',
'American Samoa' => 'as',
'Andorra' => 'ad',
'Angola' => 'ao',
'Anguilla' => 'ai',
'Antarctica' => 'aq',
'Antigua and Barbuda' => 'ag',
'Argentina' => 'ar',
'Armenia' => 'am',
'Aruba' => 'aw',
'Australia' => 'au',
'Austria' => 'at',
'Azerbaijan' => 'az',
'Bahamas' => 'bs',
'Bahrain' => 'bh',
'Bangladesh' => 'bd',
'Barbados' => 'bb',
'Belarus' => 'by',
'Belgium' => 'be',
'Belize' => 'bz',
'Benin' => 'bj',
'Bermuda' => 'bm',
'Bhutan' => 'bt',
'Bolivia' => 'bo',
'Bosnia and Herzegovina' => 'ba',
'Botswana' => 'bw',
'Bouvet Island' => 'bv',
'Brazil' => 'br',
'British Indian Ocean Territory' => 'io',
'British Virgin Islands' => 'vg',
'Brunei' => 'bn',
'Bulgaria' => 'bg',
'Burkina Faso' => 'bf',
'Burundi' => 'bi',
'Cambodia' => 'kh',
'Cameroon' => 'cm',
'Canada' => 'ca',
'Cape Verde' => 'cv',
'Cayman Islands' => 'ky',
'Central African Republic' => 'cf',
'Chad' => 'td',
'Chile' => 'cl',
'China' => 'cn',
'Christmas Island' => 'cx',
'Cocos (Keeling) Islands' => 'cc',
'Colombia' => 'co',
'Comoros' => 'km',
'Congo (Brazzaville)' => 'cg',
'Congo (Kinshasa)' => 'cd',
'Cook Islands' => 'ck',
'Costa Rica' => 'cr',
'Croatia' => 'hr',
'Cuba' => 'cu',
'Cyprus' => 'cy',
'Czech Republic' => 'cz',
'Denmark' => 'dk',
'Djibouti' => 'dj',
'Dominica' => 'dm',
'Dominican Republic' => 'do',
'East Timor' => 'tl',
'Ecuador' => 'ec',
'Egypt' => 'eg',
'El Salvador' => 'sv',
'Equatorial Guinea' => 'gq',
'Eritrea' => 'er',
'Estonia' => 'ee',
'Ethiopia' => 'et',
'Falkland Islands' => 'fk',
'Faroe Islands' => 'fo',
'Fiji' => 'fj',
'Finland' => 'fi',
'France' => 'fr',
'French Guiana' => 'gf',
'French Polynesia' => 'pf',
'French Southern Territories' => 'tf',
'Gabon' => 'ga',
'Gambia' => 'gm',
'Georgia' => 'ge',
'Germany' => 'de',
'Ghana' => 'gh',
'Gibraltar' => 'gi',
'Greece' => 'gr',
'Greenland' => 'gl',
'Grenada' => 'gd',
'Guadeloupe' => 'gp',
'Guam' => 'gu',
'Guatemala' => 'gt',
'Guernsey' => 'gg',
'Guinea' => 'gn',
'Guinea-Bissau' => 'gw',
'Guyana' => 'gy',
'Haiti' => 'ht',
'Heard Island and McDonald Islands' => 'hm',
'Honduras' => 'hn',
'Hong Kong S.A.R. China' => 'hk',
'Hungary' => 'hu',
'Iceland' => 'is',
'India' => 'in',
'Indonesia' => 'id',
'Iran' => 'ir',
'Iraq' => 'iq',
'Ireland' => 'ie',
'Isle of Man' => 'im',
'Israel' => 'il',
'Italy' => 'it',
'Ivory Coast' => 'ci',
'Jamaica' => 'jm',
'Japan' => 'jp',
'Jersey' => 'je',
'Jordan' => 'jo',
'Kazakhstan' => 'kz',
'Kenya' => 'ke',
'Kiribati' => 'ki',
'Kuwait' => 'kw',
'Kyrgyzstan' => 'kg',
'Laos' => 'la',
'Latvia' => 'lv',
'Lebanon' => 'lb',
'Lesotho' => 'ls',
'Liberia' => 'lr',
'Libya' => 'ly',
'Liechtenstein' => 'li',
'Lithuania' => 'lt',
'Luxembourg' => 'lu',
'Macao S.A.R. China' => 'mo',
'Macedonia' => 'mk',
'Madagascar' => 'mg',
'Malawi' => 'mw',
'Malaysia' => 'my',
'Maldives' => 'mv',
'Mali' => 'ml',
'Malta' => 'mt',
'Marshall Islands' => 'mh',
'Martinique' => 'mq',
'Mauritania' => 'mr',
'Mauritius' => 'mu',
'Mayotte' => 'yt',
'Mexico' => 'mx',
'Micronesia' => 'fm',
'Moldova' => 'md',
'Monaco' => 'mc',
'Mongolia' => 'mn',
'Montenegro' => 'me',
'Montserrat' => 'ms',
'Morocco' => 'ma',
'Mozambique' => 'mz',
'Myanmar' => 'mm',
'Namibia' => 'na',
'Nauru' => 'nr',
'Nepal' => 'np',
'Netherlands' => 'nl',
'Netherlands Antilles' => 'an',
'New Caledonia' => 'nc',
'New Zealand' => 'nz',
'Nicaragua' => 'ni',
'Niger' => 'ne',
'Nigeria' => 'ng',
'Niue' => 'nu',
'Norfolk Island' => 'nf',
'Northern Mariana Islands' => 'mp',
'North Korea' => 'kp',
'Norway' => 'no',
'Oman' => 'om',
'Pakistan' => 'pk',
'Palau' => 'pw',
'Palestinian Territory' => 'ps',
'Panama' => 'pa',
'Papua New Guinea' => 'pg',
'Paraguay' => 'py',
'Peru' => 'pe',
'Philippines' => 'ph',
'Pitcairn' => 'pn',
'Poland' => 'pl',
'Portugal' => 'pt',
'Puerto Rico' => 'pr',
'Qatar' => 'qa',
'Reunion' => 're',
'Romania' => 'ro',
'Russia' => 'ru',
'Rwanda' => 'rw',
'Saint Helena' => 'sh',
'Saint Kitts and Nevis' => 'kn',
'Saint Lucia' => 'lc',
'Saint Pierre and Miquelon' => 'pm',
'Saint Vincent and the Grenadines' => 'vc',
'Samoa' => 'ws',
'San Marino' => 'sm',
'Sao Tome and Principe' => 'st',
'Saudi Arabia' => 'sa',
'Senegal' => 'sn',
'Serbia' => 'rs',
'Serbia And Montenegro' => 'cs',
'Seychelles' => 'sc',
'Sierra Leone' => 'sl',
'Singapore' => 'sg',
'Slovakia' => 'sk',
'Slovenia' => 'si',
'Solomon Islands' => 'sb',
'Somalia' => 'so',
'South Africa' => 'za',
'South Georgia' => 'gs',
'South Korea' => 'kr',
'Spain' => 'es',
'Sri Lanka' => 'lk',
'Sudan' => 'sd',
'Suriname' => 'sr',
'Svalbard and Jan Mayen' => 'sj',
'Swaziland' => 'sz',
'Sweden' => 'se',
'Switzerland' => 'ch',
'Syria' => 'sy',
'Taiwan' => 'tw',
'Tajikistan' => 'tj',
'Tanzania' => 'tz',
'Thailand' => 'th',
'Togo' => 'tg',
'Tokelau' => 'tk',
'Tonga' => 'to',
'Trinidad and Tobago' => 'tt',
'Tunisia' => 'tn',
'Turkey' => 'tr',
'Turkmenistan' => 'tm',
'Turks and Caicos Islands' => 'tc',
'Tuvalu' => 'tv',
'U.S. Virgin Islands' => 'vi',
'Uganda' => 'ug',
'Ukraine' => 'ua',
'United Arab Emirates' => 'ae',
'United Kingdom' => 'gb',
'United States' => 'us',
'United States Minor Outlying Islands' => 'um',
'Uruguay' => 'uy',
'Uzbekistan' => 'uz',
'Vanuatu' => 'vu',
'Vatican' => 'va',
'Venezuela' => 've',
'Vietnam' => 'vn',
'Wallis and Futuna' => 'wf',
'Western Sahara' => 'eh',
'Yemen' => 'ye',
'Zambia' => 'zm',
'Zimbabwe' => 'zw'
                );



$listed = array(
"Albania",
"Andorra",
"Argentina",
"Australia",
"Austria",
"Belarus",
"Belgium",
"Bosnia and Herzegovina",
"Brazil",
"Bulgaria",
"Canada",
"China",
"Croatia",
"Cyprus",
"Czech Republic",
"Denmark",
"Estonia",
"Finland",
"France",
"Germany",
"Greece",
"Hong Kong S.A.R. China",
"Hungary",
"Iceland",
"India",
"Ireland",
"Italy",
"Japan",
"Latvia",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macedonia",
"Malta",
"Mexico",
"Moldova",
"Netherlands",
"New Zealand",
"Norway",
"Poland",
"Portugal",
"Romania",
"Russia",
"Serbia",
"Singapore",
"Slovakia",
"Slovenia",
"South Africa",
"Spain",
"Sweden",
"Switzerland",
"Taiwan",
"Thailand",
"Turkey",
"Ukraine",
"United Kingdom",
"United States"	);


foreach ($listed as $lookup) {
	if (isset($country_options[$lookup])) {
		echo $country_options[$lookup]." ";
	} else {
		echo "*$lookup<br>";
	}
}

?>